# File: cloudbuild.yaml
steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    #    env:
    #      - 'JDBC_URL=$JDBC_URL'
    #      - 'JDBC_USER=$JDBC_USER'
    #      - 'JDBC_PASSWORD=$JDBC_PASSWORD'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/open-covid-2-web", "."]
    # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/open-covid-2-web"]
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "open-covid-2-web",
        "--image",
        "gcr.io/$PROJECT_ID/open-covid-2-web",
        "--region",
        "us-east4",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
