const regions = [
    { value: "CALLAO", label: 'Callao'},
    { value: "LAMBAYEQUE", label: 'Lambayeque'},
    { value: "PIURA", label: 'Piura'},
    { value: "TUMBES", label: 'Tumbes'},
    { value: "APURIMAC", label: 'Apurímac'},
    { value: "AREQUIPA", label: 'Arequipa'},
    { value: "CUSCO", label: 'Cusco'},
    { value: "MADRE DE DIOS", label: 'Madre de Dios'},
    { value: "PUNO", label: 'Puno'},
    { value: "MOQUEGUA", label: 'Moquegua'},
    { value: "TACNA", label: 'Tacna'},
    { value: "ANCASH", label: 'Áncash'},
    { value: "CAJAMARCA", label: 'Cajamarca'},
    { value: "HUANUCO", label: 'Huánuco'},
    { value: "LA LIBERTAD", label: 'La Libertad'},
    { value: "PASCO", label: 'Pasco'},
    { value: "SAN MARTIN", label: 'San Martín'},
    { value: "UCAYALI", label: 'Ucayali'},
    { value: "AMAZONAS", label: 'Amazonas'},
    { value: "LORETO", label: 'Loreto'},
    { value: "AYACUCHO", label: 'Ayacucho'},
    { value: "LIMA METROPOLITANA", label: 'Lima Metropolitana'},
    { value: "HUANCAVELICA", label: 'Huancavelica'},
    { value: "ICA", label: 'Ica'},
    { value: "JUNIN", label: 'Junín'},
    { value: "LIMA REGION", label: 'Lima Región'},
]

export default regions